import type { Vacuum } from '@/types/Vacuum';

export const vacuums: Vacuum[] = [
    {
        id: 1,
        name: 'Amica Bagio Eco VM 3046',
        picture: '/src/assets/vacuums/odkurzacz1.png',
        brand: 'Amica',
        price: 299,
        power: 900,
        description: 'Urządzenie ma kompaktowe wymiary, idealnie nadaje się do małych mieszkań. System bezworkowy z pojemnikiem o pojemnikiem o poj. 1,5 l pozwala zapomnieć o zakupie i wymianie worków. To ekologiczne i ekonomiczne rozwiązanie. W zestawie Amica Bagio Eco VM3046 znajdziesz ssawki: podłogową, 2 w 1, do tapicerki oraz ssawko-szczotkę uniwersalną, za pomocą których odkurzysz cały dom - od podłóg, przez książki w regale, aż po sufit. Przewód zasilający ma 5 m długości, więc nie należy do najdłuższych, jednak zasięg pracy całego urządzenia wynosi więcej, bo 8 m.',
    },
    {
        id: 2,
        name: 'Bosch AquaWash&Clean BWD421PRO',
        picture: '/src/assets/vacuums/odkurzacz2.png',
        brand: 'Bosch',
        price: 869.99,
        power: 2100,
        description: 'To model dwufunkcyjny, który pracuje zarówno na sucho, jak i na mokro, w trybie workowym lub bezworkowym z filtrem wodnym (zbiera zanieczyszczenia do pojemnika z wodą). Bez problemu odkurzysz nim cały dom, wypierzesz dywany, wykładziny, tapicerki mebli i fotele w samochodzie. Zbierzesz też rozlane płyny z podłogi. Zadanie ułatwią ci liczne ssawki, m.in. szczelinowa, z przełącznikiem parkiet lub dywan lub turboszczotka, zwrotne kółka oraz długi kabel, gwarantujący 12-metrowy zasięg pracy urządzenia.',
    },
    {
        id: 3,
        name: 'Bosch AquaWash&Clean BWD41700',
        picture: '/src/assets/vacuums/odkurzacz3.png',
        brand: 'Bosch',
        price: 699,
        power: 1700,
        description: 'To praktyczne urządzenie wielofunkcyjne. Zdaje egzamin zarówno z odkurzania podłóg na sucho i mokro, jak i prania dywanów oraz tapicerek. Dobrze się sprawdza również w roli osuszacza, potrafi szybko wciągać rozlaną wodę czy roztopiony śnieg w przedpokoju. Pracuje przy tym efektywnie, z dużą mocą 1700 W. Model Bosch AquaWash&Clean BWD41700 wyposażono w system bezworkowy z filtrem wodnym, który zbiera zanieczyszczenia do pojemnika z wodą. Dzięki temu nie musisz się martwić o zakup i wymianę worków. W zestawie znajdziesz liczne ssawki, m.in. szczelinową, do tapicerki, z przełącznikiem parkiet/dywan oraz turboszczotkę, które ułatwią odkurzanie całego domu - od podłóg, przez książki w regale, aż po sufit. Długi kabel gwarantuje 12-metrowy zasięg pracy urządzenia.',
    },
    {
        id: 4,
        name: 'Bosch BGB38BA3T',
        picture: '/src/assets/vacuums/odkurzacz4.png',
        brand: 'Bosch',
        price: 499,
        power: 850,
        description: 'To odkurzacz workowy z Serii 4. korzystający z systemu PowerProtect (zapewnia efektywną pracę także przy zapełniającym się worku, umożliwia rzadsze wymiany worków). Oszczędności kosztów eksploatacyjnych gwarantuje również antyalergiczny filtr HEPA, zmywalny, łatwy w czyszczeniu i trwały. Zatrzymuje nawet 99,95% nieczystości, w tym drobnych cząsteczek kurzu, alergenów czy bakterii. Odkurzacz Bosch BGB38BA3T wyposażono w praktyczne rozwiązania, które ułatwiają odkurzanie całego domu. Należą do nich: duży pojemnik na kurz (4 l), system EasyClean (umożliwia szybkie i łatwe czyszczenie filtra bez konieczności dotykania brudu), a także liczne ssawki, m.in. szczelinowa, do tapicerki, z przełącznikiem parkiet/dywan oraz turboszczotkę. Długi kabel gwarantuje 12-metrowy zasięg pracy urządzenia.',
    },
    {
        id: 5,
        name: 'Bosch BGC05A322',
        picture: '/src/assets/vacuums/odkurzacz5.png',
        brand: 'Bosch',
        price: 399,
        power: 700,
        description: 'Model bezworkowy, który pozwoli ci oszczędzić pieniądze potrzebne na zakup worków. Kurz trafia tu bezpośrednio do antyalergicznego pojemnika z filtrem PureAir. Aby się pozbyć śmieci, wystarczy zwolnić dolną blokadę (bez dotykania nieczystości). Zastosowana w odkurzaczu technologia AirCycle z cyklonowym przepływem powietrza wytwarza siłę odśrodkową, która skutecznie oddziela kurz od powietrza. Natomiast filtr PureAir zapobiega ponownemu przedostawaniu się zanieczyszczeń do pomieszczenia. ',
    },
    {
        id: 6,
        name: 'Bosch ProPower BGS21POW2',
        picture: '/src/assets/vacuums/odkurzacz6.png',
        brand: 'Bosch',
        price: 629,
        power: 750,
        description: 'Ten bezworkowy model wszystkie zassane zanieczyszczenia kieruje do okrągłego pojemnika na kurz (szczelnego, higienicznego, łatwego do opróżnienia). Jego mocny silnik (z 10-letnią gwarancją producenta) oraz technologia Power AirCycle poprawiają i tak dużą efektywność odkurzania. Umożliwiają powietrzu sprawny przepływ przez odkurzacz mimo zapełniającego się pojemnika na kurz (2-litrowego). Cyklon trzykrotnie wiruje wewnątrz zbiornika, wytwarza siłę odśrodkową, która odseparowuje śmieci i pozwala im opaść na dno. Prędko i skutecznie pracują też szczotki odkurzacza. Turboszczotka z szybkoobrotowym wałkiem idealnie się nadaje co sprzątania dywanów lub wykładzin. Wyłapuje nawet najdrobniejsze pyłki, włoski i sierść.',
    },
    {
        id: 7,
        name: 'Electrolux EB51C2DB',
        picture: '/src/assets/vacuums/odkurzacz7.png',
        brand: 'Electrolux',
        price: 449,
        power: 650,
        description: 'To model workowy, który dzięki połączeniu wysokiej wydajności i przemyślanej konstrukcji zyskał uznanie ekspertów oraz klientów. Jego silnik o mocy 650 W gwarantuje skuteczne odkurzanie różnych powierzchni, a uniwersalna szczotka AllFloor nadaje się zarówno do dywanów, wykładzin, jak i podłóg twardych. Alergicy doceniają w tym odkurzaczu filtr HEPA 13, który zatrzymuje aż do 99,99% cząsteczek kurzu i alergenów wielkości zaledwie 0,3 μm, jednocześnie zapewniając czystsze powietrze w pomieszczeniu. Wszyscy użytkownicy chwalą płynną regulację mocy ssania, duży zasięg pracy (8,5 m), miękkie koła (które chronią podłogi przed zarysowaniami i wspomagają manewrowanie sprzętem) oraz wygodną rurę teleskopową, łatwą do dopasowania do wzrostu użytkownika.',
    },
    {
        id: 8,
        name: 'Electrolux Pure D82- ALRG Silence',
        picture: '/src/assets/vacuums/odkurzacz8.png',
        brand: 'Electrolux',
        price: 979,
        power: 500,
        description: 'Potrzebujesz odkurzacza, który nie stawia wszystkich domowników na nogi? Pracuje cicho i skutecznie? Dba o samopoczucie osób uczulonych na roztocza i pyłki? Oto on model workowy Pure D82-ALRG Silence. Emituje głośność o natężeniu 57 dB (to tyle co spokojna rozmowa w domu). Nie powinien więc wybudzać dziecka ze snu czy przeszkadzać w nauce. Dzięki filtrowi Allergy Plus w 99,95% oczyszcza powietrze wylotowe z odkurzacza, zatrzymuje nie tylko kurz, ale też najdrobniejsze cząsteczki odpowiedzialne za skórne i oddechowe reakcje alergiczne. To urządzenie nowej generacji, które samodzielnie rozpoznaje rodzaj podłogi pod szczotką. Pracując w trybie SmartMode, potrafi automatycznie dopasowywać moc ssania do odkurzanej powierzchni.',
    },
    {
        id: 9,
        name: 'Electrolux UltraOne EUOC94DB',
        picture: '/src/assets/vacuums/odkurzacz9.png',
        brand: 'Electrolux',
        price: 699,
        power: 700,
        description: 'Dzięki wydajnej ssawce SlowMotion Silent oraz uszczelnionej drodze przepływu powietrza cechuje go wysoka wydajność odkurzania. Nie emituje przy tym dokuczliwego hałasu, jego głośność wynosi około 66 dB. To efekt zastosowania technologii Silent Air, wyciszenia węża i ssawki FlowMotion Extreme. Odkurzacz sprzyja osobom uczulonym na roztocza, pyłki i sierść zwierząt. Jego filtr Allergy Plus wychwytuje aż 99,95% zanieczyszczeń, w tym alergenów i drobnoustrojów. Waży prawie 8 kg, więc niemało, ale jego przenoszenie ułatwia duży, wygodny uchwyt. Miękko wykończone koła są delikatne dla podłóg. Powstawaniu uszkodzeń podczas sprzątania zapobiega też specjalna szczotka do parkietu i powierzchni podatnych na zarysowania.',
    }
]
